version: '3'
services:
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - service1
      - service2
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:8000"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:8000"