version: '3'
services:
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - service1
      - service2
  service1:
    image: frankiewfli/qrcoderedemption:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "9191:8001"
  service2:
    image: frankiewfli/qrcoderedemption:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "9292:8001"