   CREATE TABLE "DB"."QRCODE_REDEMPTION_LOG"
   (
    "ID" NUMBER(10) not null,
	"CARDID" VARCHAR2(200 char),
    "CARDTYPE" NUMBER(6),
    "QRCODE" VARCHAR2(2000 char),
    "REDEMPTIONID" VARCHAR2(10 char),
    "MESSAGE" VARCHAR2(2000 char),
    "DEVICEID" Number(6),
    "CREATEDATE" Date,
    "STATUS"  VARCHAR2(100 char)
   );
   ALTER TABLE QRCODE_REDEMPTION_LOG ADD (CONSTRAINT ID PRIMARY KEY (ID));
   CREATE SEQUENCE  ID_SEQUENCE START WITH 1;

CREATE OR REPLACE TRIGGER qrcode_id_bir
BEFORE INSERT ON QRCODE_REDEMPTION_LOG
FOR EACH ROW

BEGIN
  SELECT QRCODE_Id_seq.NEXTVAL
  INTO   :NEW.id
  FROM   dual;
END;
