# FROM nginx:latest
# RUN rm /etc/nginx/conf.d/default.conf
# COPY /conf.d/nginx.conf /etc/nginx/conf.d/default.conf

FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx.conf /etc/nginx/conf.d/default.conf